name: Python ML CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 4. Install dependencies
      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      # 5. Verify installations
      - name: Check Python and pytest
        run: |
          python --version
          python -m pip --version
          python -m pytest --version

      # 6. Run tests
      - name: Run tests
        run: python -m pytest -v tests/test_model.py

      # 7. Train model (optional)
      - name: Train model
        run: python train.py
