name: Python ML CI

# Trigger workflow on push or pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Check Python and pip versions (debug)
      - name: Check Python and pip
        run: |
          python --version
          python3 --version
          python -m pip --version

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # 5. Run tests using pytest
      - name: Run tests
        run: python -m pytest tests/

      # 6. Train ML model
      - name: Train model
        run: python train.py
